version: '3.9'

services:

  autotrader-service:
    container_name: autotrader-service
    build: ./autotrader-service
    restart:
      on-failure
    ports:
      # http://localhost:5050
      - "5000:5000"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://autotrader-service:example@mongo:27017/autotrader
    depends_on:
      - "mongo"
    networks:
      - backend

  mongo:
    container_name: mongodb
    image: mongo
    command: mongod --quiet --logpath /dev/null
    restart: always
    ports:
      # mongodb://root:example@0.0.0.0:27017/
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend
networks:
  backend: { }